// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id, category, timestamp, user_id, subject, action,
    purpose, requesting_party, decision, reason,
    email, request_id, actor_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO NOTHING
`

type InsertAuditEventParams struct {
	ID              uuid.UUID
	Category        string
	Timestamp       time.Time
	UserID          uuid.NullUUID
	Subject         string
	Action          string
	Purpose         string
	RequestingParty string
	Decision        string
	Reason          string
	Email           string
	RequestID       string
	ActorID         string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ID,
		arg.Category,
		arg.Timestamp,
		arg.UserID,
		arg.Subject,
		arg.Action,
		arg.Purpose,
		arg.RequestingParty,
		arg.Decision,
		arg.Reason,
		arg.Email,
		arg.RequestID,
		arg.ActorID,
	)
	return err
}

const insertOutboxEntry = `-- name: InsertOutboxEntry :exec
INSERT INTO outbox (id, aggregate_type, aggregate_id, event_type, payload, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEntryParams struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       json.RawMessage
	CreatedAt     time.Time
}

func (q *Queries) InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertOutboxEntry,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT category, timestamp, user_id, subject, action,
       purpose, requesting_party, decision, reason,
       email, request_id, actor_id
FROM audit_events
ORDER BY timestamp DESC
`

type ListAuditEventsRow struct {
	Category        string
	Timestamp       time.Time
	UserID          uuid.NullUUID
	Subject         string
	Action          string
	Purpose         string
	RequestingParty string
	Decision        string
	Reason          string
	Email           string
	RequestID       string
	ActorID         string
}

func (q *Queries) ListAuditEvents(ctx context.Context) ([]ListAuditEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsRow
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.Category,
			&i.Timestamp,
			&i.UserID,
			&i.Subject,
			&i.Action,
			&i.Purpose,
			&i.RequestingParty,
			&i.Decision,
			&i.Reason,
			&i.Email,
			&i.RequestID,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByUser = `-- name: ListAuditEventsByUser :many
SELECT category, timestamp, user_id, subject, action,
       purpose, requesting_party, decision, reason,
       email, request_id, actor_id
FROM audit_events
WHERE user_id = $1
ORDER BY timestamp DESC
`

type ListAuditEventsByUserRow struct {
	Category        string
	Timestamp       time.Time
	UserID          uuid.NullUUID
	Subject         string
	Action          string
	Purpose         string
	RequestingParty string
	Decision        string
	Reason          string
	Email           string
	RequestID       string
	ActorID         string
}

func (q *Queries) ListAuditEventsByUser(ctx context.Context, userID uuid.NullUUID) ([]ListAuditEventsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsByUserRow
	for rows.Next() {
		var i ListAuditEventsByUserRow
		if err := rows.Scan(
			&i.Category,
			&i.Timestamp,
			&i.UserID,
			&i.Subject,
			&i.Action,
			&i.Purpose,
			&i.RequestingParty,
			&i.Decision,
			&i.Reason,
			&i.Email,
			&i.RequestID,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditEvents = `-- name: ListRecentAuditEvents :many
SELECT category, timestamp, user_id, subject, action,
       purpose, requesting_party, decision, reason,
       email, request_id, actor_id
FROM audit_events
ORDER BY timestamp DESC
LIMIT $1
`

type ListRecentAuditEventsRow struct {
	Category        string
	Timestamp       time.Time
	UserID          uuid.NullUUID
	Subject         string
	Action          string
	Purpose         string
	RequestingParty string
	Decision        string
	Reason          string
	Email           string
	RequestID       string
	ActorID         string
}

func (q *Queries) ListRecentAuditEvents(ctx context.Context, limit int32) ([]ListRecentAuditEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAuditEventsRow
	for rows.Next() {
		var i ListRecentAuditEventsRow
		if err := rows.Scan(
			&i.Category,
			&i.Timestamp,
			&i.UserID,
			&i.Subject,
			&i.Action,
			&i.Purpose,
			&i.RequestingParty,
			&i.Decision,
			&i.Reason,
			&i.Email,
			&i.RequestID,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
