// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package sqlc

import (
	"context"
	"time"
)

const getCitizenCache = `-- name: GetCitizenCache :one
SELECT national_id, full_name, date_of_birth, address, valid, source, checked_at, regulated
FROM citizen_cache
WHERE national_id = $1 AND regulated = $2 AND checked_at >= $3
`

type GetCitizenCacheParams struct {
	NationalID string
	Regulated  bool
	CheckedAt  time.Time
}

func (q *Queries) GetCitizenCache(ctx context.Context, arg GetCitizenCacheParams) (CitizenCache, error) {
	row := q.db.QueryRowContext(ctx, getCitizenCache, arg.NationalID, arg.Regulated, arg.CheckedAt)
	var i CitizenCache
	err := row.Scan(
		&i.NationalID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Address,
		&i.Valid,
		&i.Source,
		&i.CheckedAt,
		&i.Regulated,
	)
	return i, err
}

const getSanctionsCache = `-- name: GetSanctionsCache :one
SELECT national_id, listed, source, checked_at
FROM sanctions_cache
WHERE national_id = $1 AND checked_at >= $2
`

type GetSanctionsCacheParams struct {
	NationalID string
	CheckedAt  time.Time
}

func (q *Queries) GetSanctionsCache(ctx context.Context, arg GetSanctionsCacheParams) (SanctionsCache, error) {
	row := q.db.QueryRowContext(ctx, getSanctionsCache, arg.NationalID, arg.CheckedAt)
	var i SanctionsCache
	err := row.Scan(
		&i.NationalID,
		&i.Listed,
		&i.Source,
		&i.CheckedAt,
	)
	return i, err
}

const upsertCitizenCache = `-- name: UpsertCitizenCache :exec
INSERT INTO citizen_cache (
    national_id, full_name, date_of_birth, address, valid, source, checked_at, regulated
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (national_id, regulated) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    date_of_birth = EXCLUDED.date_of_birth,
    address = EXCLUDED.address,
    valid = EXCLUDED.valid,
    source = EXCLUDED.source,
    checked_at = EXCLUDED.checked_at
`

type UpsertCitizenCacheParams struct {
	NationalID  string
	FullName    string
	DateOfBirth string
	Address     string
	Valid       bool
	Source      string
	CheckedAt   time.Time
	Regulated   bool
}

func (q *Queries) UpsertCitizenCache(ctx context.Context, arg UpsertCitizenCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCitizenCache,
		arg.NationalID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Address,
		arg.Valid,
		arg.Source,
		arg.CheckedAt,
		arg.Regulated,
	)
	return err
}

const upsertSanctionsCache = `-- name: UpsertSanctionsCache :exec
INSERT INTO sanctions_cache (national_id, listed, source, checked_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (national_id) DO UPDATE SET
    listed = EXCLUDED.listed,
    source = EXCLUDED.source,
    checked_at = EXCLUDED.checked_at
`

type UpsertSanctionsCacheParams struct {
	NationalID string
	Listed     bool
	Source     string
	CheckedAt  time.Time
}

func (q *Queries) UpsertSanctionsCache(ctx context.Context, arg UpsertSanctionsCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertSanctionsCache,
		arg.NationalID,
		arg.Listed,
		arg.Source,
		arg.CheckedAt,
	)
	return err
}
