// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, type, subject_id, issuer, issued_at,
    CASE WHEN type = 'AgeOver18' THEN NULL::jsonb ELSE claims END AS claims,
    is_over_18, verified_via
FROM vc_credentials
WHERE id = $1
`

type GetCredentialByIDRow struct {
	ID          string
	Type        string
	SubjectID   uuid.UUID
	Issuer      string
	IssuedAt    time.Time
	Claims      interface{}
	IsOver18    sql.NullBool
	VerifiedVia sql.NullString
}

func (q *Queries) GetCredentialByID(ctx context.Context, id string) (GetCredentialByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByID, id)
	var i GetCredentialByIDRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SubjectID,
		&i.Issuer,
		&i.IssuedAt,
		&i.Claims,
		&i.IsOver18,
		&i.VerifiedVia,
	)
	return i, err
}

const getCredentialBySubjectAndType = `-- name: GetCredentialBySubjectAndType :one
SELECT id, type, subject_id, issuer, issued_at,
    CASE WHEN type = 'AgeOver18' THEN NULL::jsonb ELSE claims END AS claims,
    is_over_18, verified_via
FROM vc_credentials
WHERE subject_id = $1 AND type = $2
ORDER BY issued_at DESC
LIMIT 1
`

type GetCredentialBySubjectAndTypeParams struct {
	SubjectID uuid.UUID
	Type      string
}

type GetCredentialBySubjectAndTypeRow struct {
	ID          string
	Type        string
	SubjectID   uuid.UUID
	Issuer      string
	IssuedAt    time.Time
	Claims      interface{}
	IsOver18    sql.NullBool
	VerifiedVia sql.NullString
}

func (q *Queries) GetCredentialBySubjectAndType(ctx context.Context, arg GetCredentialBySubjectAndTypeParams) (GetCredentialBySubjectAndTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getCredentialBySubjectAndType, arg.SubjectID, arg.Type)
	var i GetCredentialBySubjectAndTypeRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.SubjectID,
		&i.Issuer,
		&i.IssuedAt,
		&i.Claims,
		&i.IsOver18,
		&i.VerifiedVia,
	)
	return i, err
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO vc_credentials (id, type, subject_id, issuer, issued_at, claims, is_over_18, verified_via)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type,
    subject_id = EXCLUDED.subject_id,
    issuer = EXCLUDED.issuer,
    issued_at = EXCLUDED.issued_at,
    claims = EXCLUDED.claims,
    is_over_18 = EXCLUDED.is_over_18,
    verified_via = EXCLUDED.verified_via
`

type UpsertCredentialParams struct {
	ID          string
	Type        string
	SubjectID   uuid.UUID
	Issuer      string
	IssuedAt    time.Time
	Claims      json.RawMessage
	IsOver18    sql.NullBool
	VerifiedVia sql.NullString
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredential,
		arg.ID,
		arg.Type,
		arg.SubjectID,
		arg.Issuer,
		arg.IssuedAt,
		arg.Claims,
		arg.IsOver18,
		arg.VerifiedVia,
	)
	return err
}
