// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_throttle.sql

package sqlc

import (
	"context"
	"time"
)

const getGlobalThrottleBucket = `-- name: GetGlobalThrottleBucket :one
SELECT bucket_start, count
FROM global_throttle
WHERE bucket_type = $1
`

type GetGlobalThrottleBucketRow struct {
	BucketStart time.Time
	Count       int32
}

func (q *Queries) GetGlobalThrottleBucket(ctx context.Context, bucketType string) (GetGlobalThrottleBucketRow, error) {
	row := q.db.QueryRowContext(ctx, getGlobalThrottleBucket, bucketType)
	var i GetGlobalThrottleBucketRow
	err := row.Scan(&i.BucketStart, &i.Count)
	return i, err
}

const getGlobalThrottleBucketForUpdate = `-- name: GetGlobalThrottleBucketForUpdate :one
SELECT bucket_start, count
FROM global_throttle
WHERE bucket_type = $1
FOR UPDATE
`

type GetGlobalThrottleBucketForUpdateRow struct {
	BucketStart time.Time
	Count       int32
}

func (q *Queries) GetGlobalThrottleBucketForUpdate(ctx context.Context, bucketType string) (GetGlobalThrottleBucketForUpdateRow, error) {
	row := q.db.QueryRowContext(ctx, getGlobalThrottleBucketForUpdate, bucketType)
	var i GetGlobalThrottleBucketForUpdateRow
	err := row.Scan(&i.BucketStart, &i.Count)
	return i, err
}

const insertGlobalThrottleBucket = `-- name: InsertGlobalThrottleBucket :exec
INSERT INTO global_throttle (bucket_type, bucket_start, count)
VALUES ($1, $2, 0)
ON CONFLICT (bucket_type) DO NOTHING
`

type InsertGlobalThrottleBucketParams struct {
	BucketType  string
	BucketStart time.Time
}

func (q *Queries) InsertGlobalThrottleBucket(ctx context.Context, arg InsertGlobalThrottleBucketParams) error {
	_, err := q.db.ExecContext(ctx, insertGlobalThrottleBucket, arg.BucketType, arg.BucketStart)
	return err
}

const updateGlobalThrottleBucket = `-- name: UpdateGlobalThrottleBucket :exec
UPDATE global_throttle
SET bucket_start = $2, count = $3
WHERE bucket_type = $1
`

type UpdateGlobalThrottleBucketParams struct {
	BucketType  string
	BucketStart time.Time
	Count       int32
}

func (q *Queries) UpdateGlobalThrottleBucket(ctx context.Context, arg UpdateGlobalThrottleBucketParams) error {
	_, err := q.db.ExecContext(ctx, updateGlobalThrottleBucket, arg.BucketType, arg.BucketStart, arg.Count)
	return err
}
