// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/consent.proto

package consentpb

import (
	common "github.com/credo/gateway/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Purpose enum matching internal consent.Purpose
type Purpose int32

const (
	Purpose_PURPOSE_UNSPECIFIED            Purpose = 0
	Purpose_PURPOSE_LOGIN                  Purpose = 1
	Purpose_PURPOSE_REGISTRY_CHECK         Purpose = 2
	Purpose_PURPOSE_VC_ISSUANCE            Purpose = 3
	Purpose_PURPOSE_DECISION_EVALUATION    Purpose = 4
	Purpose_PURPOSE_BIOMETRIC_VERIFICATION Purpose = 5
)

// Enum value maps for Purpose.
var (
	Purpose_name = map[int32]string{
		0: "PURPOSE_UNSPECIFIED",
		1: "PURPOSE_LOGIN",
		2: "PURPOSE_REGISTRY_CHECK",
		3: "PURPOSE_VC_ISSUANCE",
		4: "PURPOSE_DECISION_EVALUATION",
		5: "PURPOSE_BIOMETRIC_VERIFICATION",
	}
	Purpose_value = map[string]int32{
		"PURPOSE_UNSPECIFIED":            0,
		"PURPOSE_LOGIN":                  1,
		"PURPOSE_REGISTRY_CHECK":         2,
		"PURPOSE_VC_ISSUANCE":            3,
		"PURPOSE_DECISION_EVALUATION":    4,
		"PURPOSE_BIOMETRIC_VERIFICATION": 5,
	}
)

func (x Purpose) Enum() *Purpose {
	p := new(Purpose)
	*p = x
	return p
}

func (x Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_consent_proto_enumTypes[0].Descriptor()
}

func (Purpose) Type() protoreflect.EnumType {
	return &file_api_proto_consent_proto_enumTypes[0]
}

func (x Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Purpose.Descriptor instead.
func (Purpose) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{0}
}

// Consent status
type ConsentStatus int32

const (
	ConsentStatus_CONSENT_STATUS_UNSPECIFIED ConsentStatus = 0
	ConsentStatus_CONSENT_STATUS_ACTIVE      ConsentStatus = 1
	ConsentStatus_CONSENT_STATUS_EXPIRED     ConsentStatus = 2
	ConsentStatus_CONSENT_STATUS_REVOKED     ConsentStatus = 3
)

// Enum value maps for ConsentStatus.
var (
	ConsentStatus_name = map[int32]string{
		0: "CONSENT_STATUS_UNSPECIFIED",
		1: "CONSENT_STATUS_ACTIVE",
		2: "CONSENT_STATUS_EXPIRED",
		3: "CONSENT_STATUS_REVOKED",
	}
	ConsentStatus_value = map[string]int32{
		"CONSENT_STATUS_UNSPECIFIED": 0,
		"CONSENT_STATUS_ACTIVE":      1,
		"CONSENT_STATUS_EXPIRED":     2,
		"CONSENT_STATUS_REVOKED":     3,
	}
)

func (x ConsentStatus) Enum() *ConsentStatus {
	p := new(ConsentStatus)
	*p = x
	return p
}

func (x ConsentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_consent_proto_enumTypes[1].Descriptor()
}

func (ConsentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_consent_proto_enumTypes[1]
}

func (x ConsentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsentStatus.Descriptor instead.
func (ConsentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{1}
}

// HasConsentRequest checks if user has valid consent
type HasConsentRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose       Purpose                 `protobuf:"varint,3,opt,name=purpose,proto3,enum=credo.consent.v1.Purpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasConsentRequest) Reset() {
	*x = HasConsentRequest{}
	mi := &file_api_proto_consent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasConsentRequest) ProtoMessage() {}

func (x *HasConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasConsentRequest.ProtoReflect.Descriptor instead.
func (*HasConsentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{0}
}

func (x *HasConsentRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HasConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HasConsentRequest) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_PURPOSE_UNSPECIFIED
}

type HasConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasConsent    bool                   `protobuf:"varint,1,opt,name=has_consent,json=hasConsent,proto3" json:"has_consent,omitempty"`
	Status        ConsentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=credo.consent.v1.ConsentStatus" json:"status,omitempty"`
	GrantedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasConsentResponse) Reset() {
	*x = HasConsentResponse{}
	mi := &file_api_proto_consent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasConsentResponse) ProtoMessage() {}

func (x *HasConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasConsentResponse.ProtoReflect.Descriptor instead.
func (*HasConsentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{1}
}

func (x *HasConsentResponse) GetHasConsent() bool {
	if x != nil {
		return x.HasConsent
	}
	return false
}

func (x *HasConsentResponse) GetStatus() ConsentStatus {
	if x != nil {
		return x.Status
	}
	return ConsentStatus_CONSENT_STATUS_UNSPECIFIED
}

func (x *HasConsentResponse) GetGrantedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrantedAt
	}
	return nil
}

func (x *HasConsentResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// RequireConsentRequest enforces consent requirement
type RequireConsentRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose       Purpose                 `protobuf:"varint,3,opt,name=purpose,proto3,enum=credo.consent.v1.Purpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequireConsentRequest) Reset() {
	*x = RequireConsentRequest{}
	mi := &file_api_proto_consent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequireConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireConsentRequest) ProtoMessage() {}

func (x *RequireConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireConsentRequest.ProtoReflect.Descriptor instead.
func (*RequireConsentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{2}
}

func (x *RequireConsentRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequireConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequireConsentRequest) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_PURPOSE_UNSPECIFIED
}

type RequireConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // Empty if allowed, error reason if not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequireConsentResponse) Reset() {
	*x = RequireConsentResponse{}
	mi := &file_api_proto_consent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequireConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireConsentResponse) ProtoMessage() {}

func (x *RequireConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireConsentResponse.ProtoReflect.Descriptor instead.
func (*RequireConsentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{3}
}

func (x *RequireConsentResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RequireConsentResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GrantConsentRequest grants consent
type GrantConsentRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purposes      []Purpose               `protobuf:"varint,3,rep,packed,name=purposes,proto3,enum=credo.consent.v1.Purpose" json:"purposes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantConsentRequest) Reset() {
	*x = GrantConsentRequest{}
	mi := &file_api_proto_consent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantConsentRequest) ProtoMessage() {}

func (x *GrantConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantConsentRequest.ProtoReflect.Descriptor instead.
func (*GrantConsentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{4}
}

func (x *GrantConsentRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrantConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantConsentRequest) GetPurposes() []Purpose {
	if x != nil {
		return x.Purposes
	}
	return nil
}

type GrantConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       []*ConsentRecord       `protobuf:"bytes,1,rep,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantConsentResponse) Reset() {
	*x = GrantConsentResponse{}
	mi := &file_api_proto_consent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantConsentResponse) ProtoMessage() {}

func (x *GrantConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantConsentResponse.ProtoReflect.Descriptor instead.
func (*GrantConsentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{5}
}

func (x *GrantConsentResponse) GetGranted() []*ConsentRecord {
	if x != nil {
		return x.Granted
	}
	return nil
}

// RevokeConsentRequest revokes consent
type RevokeConsentRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purposes      []Purpose               `protobuf:"varint,3,rep,packed,name=purposes,proto3,enum=credo.consent.v1.Purpose" json:"purposes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentRequest) Reset() {
	*x = RevokeConsentRequest{}
	mi := &file_api_proto_consent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentRequest) ProtoMessage() {}

func (x *RevokeConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentRequest.ProtoReflect.Descriptor instead.
func (*RevokeConsentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeConsentRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RevokeConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeConsentRequest) GetPurposes() []Purpose {
	if x != nil {
		return x.Purposes
	}
	return nil
}

type RevokeConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       []*ConsentRecord       `protobuf:"bytes,1,rep,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentResponse) Reset() {
	*x = RevokeConsentResponse{}
	mi := &file_api_proto_consent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentResponse) ProtoMessage() {}

func (x *RevokeConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentResponse.ProtoReflect.Descriptor instead.
func (*RevokeConsentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeConsentResponse) GetRevoked() []*ConsentRecord {
	if x != nil {
		return x.Revoked
	}
	return nil
}

// ListConsentsRequest lists all consents
type ListConsentsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StatusFilter  ConsentStatus           `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=credo.consent.v1.ConsentStatus" json:"status_filter,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsentsRequest) Reset() {
	*x = ListConsentsRequest{}
	mi := &file_api_proto_consent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsentsRequest) ProtoMessage() {}

func (x *ListConsentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsentsRequest.ProtoReflect.Descriptor instead.
func (*ListConsentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{8}
}

func (x *ListConsentsRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ListConsentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListConsentsRequest) GetStatusFilter() ConsentStatus {
	if x != nil {
		return x.StatusFilter
	}
	return ConsentStatus_CONSENT_STATUS_UNSPECIFIED
}

type ListConsentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consents      []*ConsentRecord       `protobuf:"bytes,1,rep,name=consents,proto3" json:"consents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsentsResponse) Reset() {
	*x = ListConsentsResponse{}
	mi := &file_api_proto_consent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsentsResponse) ProtoMessage() {}

func (x *ListConsentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsentsResponse.ProtoReflect.Descriptor instead.
func (*ListConsentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{9}
}

func (x *ListConsentsResponse) GetConsents() []*ConsentRecord {
	if x != nil {
		return x.Consents
	}
	return nil
}

// ConsentRecord represents a consent record
type ConsentRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose       Purpose                `protobuf:"varint,3,opt,name=purpose,proto3,enum=credo.consent.v1.Purpose" json:"purpose,omitempty"`
	GrantedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Status        ConsentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=credo.consent.v1.ConsentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsentRecord) Reset() {
	*x = ConsentRecord{}
	mi := &file_api_proto_consent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentRecord) ProtoMessage() {}

func (x *ConsentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_consent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentRecord.ProtoReflect.Descriptor instead.
func (*ConsentRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_consent_proto_rawDescGZIP(), []int{10}
}

func (x *ConsentRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsentRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsentRecord) GetPurpose() Purpose {
	if x != nil {
		return x.Purpose
	}
	return Purpose_PURPOSE_UNSPECIFIED
}

func (x *ConsentRecord) GetGrantedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrantedAt
	}
	return nil
}

func (x *ConsentRecord) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ConsentRecord) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *ConsentRecord) GetStatus() ConsentStatus {
	if x != nil {
		return x.Status
	}
	return ConsentStatus_CONSENT_STATUS_UNSPECIFIED
}

var File_api_proto_consent_proto protoreflect.FileDescriptor

const file_api_proto_consent_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/consent.proto\x12\x10credo.consent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16api/proto/common.proto\"\x9f\x01\n" +
	"\x11HasConsentRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x19.credo.consent.v1.PurposeR\apurpose\"\xe4\x01\n" +
	"\x12HasConsentResponse\x12\x1f\n" +
	"\vhas_consent\x18\x01 \x01(\bR\n" +
	"hasConsent\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.credo.consent.v1.ConsentStatusR\x06status\x129\n" +
	"\n" +
	"granted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tgrantedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa3\x01\n" +
	"\x15RequireConsentRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x19.credo.consent.v1.PurposeR\apurpose\"J\n" +
	"\x16RequireConsentResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa3\x01\n" +
	"\x13GrantConsentRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x125\n" +
	"\bpurposes\x18\x03 \x03(\x0e2\x19.credo.consent.v1.PurposeR\bpurposes\"Q\n" +
	"\x14GrantConsentResponse\x129\n" +
	"\agranted\x18\x01 \x03(\v2\x1f.credo.consent.v1.ConsentRecordR\agranted\"\xa4\x01\n" +
	"\x14RevokeConsentRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x125\n" +
	"\bpurposes\x18\x03 \x03(\x0e2\x19.credo.consent.v1.PurposeR\bpurposes\"R\n" +
	"\x15RevokeConsentResponse\x129\n" +
	"\arevoked\x18\x01 \x03(\v2\x1f.credo.consent.v1.ConsentRecordR\arevoked\"\xb2\x01\n" +
	"\x13ListConsentsRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12D\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2\x1f.credo.consent.v1.ConsentStatusR\fstatusFilter\"S\n" +
	"\x14ListConsentsResponse\x12;\n" +
	"\bconsents\x18\x01 \x03(\v2\x1f.credo.consent.v1.ConsentRecordR\bconsents\"\xd7\x02\n" +
	"\rConsentRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x19.credo.consent.v1.PurposeR\apurpose\x129\n" +
	"\n" +
	"granted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tgrantedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"revoked_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.credo.consent.v1.ConsentStatusR\x06status*\xaf\x01\n" +
	"\aPurpose\x12\x17\n" +
	"\x13PURPOSE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPURPOSE_LOGIN\x10\x01\x12\x1a\n" +
	"\x16PURPOSE_REGISTRY_CHECK\x10\x02\x12\x17\n" +
	"\x13PURPOSE_VC_ISSUANCE\x10\x03\x12\x1f\n" +
	"\x1bPURPOSE_DECISION_EVALUATION\x10\x04\x12\"\n" +
	"\x1ePURPOSE_BIOMETRIC_VERIFICATION\x10\x05*\x82\x01\n" +
	"\rConsentStatus\x12\x1e\n" +
	"\x1aCONSENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONSENT_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16CONSENT_STATUS_EXPIRED\x10\x02\x12\x1a\n" +
	"\x16CONSENT_STATUS_REVOKED\x10\x032\xee\x03\n" +
	"\x0eConsentService\x12W\n" +
	"\n" +
	"HasConsent\x12#.credo.consent.v1.HasConsentRequest\x1a$.credo.consent.v1.HasConsentResponse\x12c\n" +
	"\x0eRequireConsent\x12'.credo.consent.v1.RequireConsentRequest\x1a(.credo.consent.v1.RequireConsentResponse\x12]\n" +
	"\fGrantConsent\x12%.credo.consent.v1.GrantConsentRequest\x1a&.credo.consent.v1.GrantConsentResponse\x12`\n" +
	"\rRevokeConsent\x12&.credo.consent.v1.RevokeConsentRequest\x1a'.credo.consent.v1.RevokeConsentResponse\x12]\n" +
	"\fListConsents\x12%.credo.consent.v1.ListConsentsRequest\x1a&.credo.consent.v1.ListConsentsResponseB6Z4github.com/credo/gateway/api/proto/consent;consentpbb\x06proto3"

var (
	file_api_proto_consent_proto_rawDescOnce sync.Once
	file_api_proto_consent_proto_rawDescData []byte
)

func file_api_proto_consent_proto_rawDescGZIP() []byte {
	file_api_proto_consent_proto_rawDescOnce.Do(func() {
		file_api_proto_consent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_consent_proto_rawDesc), len(file_api_proto_consent_proto_rawDesc)))
	})
	return file_api_proto_consent_proto_rawDescData
}

var file_api_proto_consent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_consent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_consent_proto_goTypes = []any{
	(Purpose)(0),                   // 0: credo.consent.v1.Purpose
	(ConsentStatus)(0),             // 1: credo.consent.v1.ConsentStatus
	(*HasConsentRequest)(nil),      // 2: credo.consent.v1.HasConsentRequest
	(*HasConsentResponse)(nil),     // 3: credo.consent.v1.HasConsentResponse
	(*RequireConsentRequest)(nil),  // 4: credo.consent.v1.RequireConsentRequest
	(*RequireConsentResponse)(nil), // 5: credo.consent.v1.RequireConsentResponse
	(*GrantConsentRequest)(nil),    // 6: credo.consent.v1.GrantConsentRequest
	(*GrantConsentResponse)(nil),   // 7: credo.consent.v1.GrantConsentResponse
	(*RevokeConsentRequest)(nil),   // 8: credo.consent.v1.RevokeConsentRequest
	(*RevokeConsentResponse)(nil),  // 9: credo.consent.v1.RevokeConsentResponse
	(*ListConsentsRequest)(nil),    // 10: credo.consent.v1.ListConsentsRequest
	(*ListConsentsResponse)(nil),   // 11: credo.consent.v1.ListConsentsResponse
	(*ConsentRecord)(nil),          // 12: credo.consent.v1.ConsentRecord
	(*common.RequestMetadata)(nil), // 13: credo.common.v1.RequestMetadata
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_api_proto_consent_proto_depIdxs = []int32{
	13, // 0: credo.consent.v1.HasConsentRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	0,  // 1: credo.consent.v1.HasConsentRequest.purpose:type_name -> credo.consent.v1.Purpose
	1,  // 2: credo.consent.v1.HasConsentResponse.status:type_name -> credo.consent.v1.ConsentStatus
	14, // 3: credo.consent.v1.HasConsentResponse.granted_at:type_name -> google.protobuf.Timestamp
	14, // 4: credo.consent.v1.HasConsentResponse.expires_at:type_name -> google.protobuf.Timestamp
	13, // 5: credo.consent.v1.RequireConsentRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	0,  // 6: credo.consent.v1.RequireConsentRequest.purpose:type_name -> credo.consent.v1.Purpose
	13, // 7: credo.consent.v1.GrantConsentRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	0,  // 8: credo.consent.v1.GrantConsentRequest.purposes:type_name -> credo.consent.v1.Purpose
	12, // 9: credo.consent.v1.GrantConsentResponse.granted:type_name -> credo.consent.v1.ConsentRecord
	13, // 10: credo.consent.v1.RevokeConsentRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	0,  // 11: credo.consent.v1.RevokeConsentRequest.purposes:type_name -> credo.consent.v1.Purpose
	12, // 12: credo.consent.v1.RevokeConsentResponse.revoked:type_name -> credo.consent.v1.ConsentRecord
	13, // 13: credo.consent.v1.ListConsentsRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	1,  // 14: credo.consent.v1.ListConsentsRequest.status_filter:type_name -> credo.consent.v1.ConsentStatus
	12, // 15: credo.consent.v1.ListConsentsResponse.consents:type_name -> credo.consent.v1.ConsentRecord
	0,  // 16: credo.consent.v1.ConsentRecord.purpose:type_name -> credo.consent.v1.Purpose
	14, // 17: credo.consent.v1.ConsentRecord.granted_at:type_name -> google.protobuf.Timestamp
	14, // 18: credo.consent.v1.ConsentRecord.expires_at:type_name -> google.protobuf.Timestamp
	14, // 19: credo.consent.v1.ConsentRecord.revoked_at:type_name -> google.protobuf.Timestamp
	1,  // 20: credo.consent.v1.ConsentRecord.status:type_name -> credo.consent.v1.ConsentStatus
	2,  // 21: credo.consent.v1.ConsentService.HasConsent:input_type -> credo.consent.v1.HasConsentRequest
	4,  // 22: credo.consent.v1.ConsentService.RequireConsent:input_type -> credo.consent.v1.RequireConsentRequest
	6,  // 23: credo.consent.v1.ConsentService.GrantConsent:input_type -> credo.consent.v1.GrantConsentRequest
	8,  // 24: credo.consent.v1.ConsentService.RevokeConsent:input_type -> credo.consent.v1.RevokeConsentRequest
	10, // 25: credo.consent.v1.ConsentService.ListConsents:input_type -> credo.consent.v1.ListConsentsRequest
	3,  // 26: credo.consent.v1.ConsentService.HasConsent:output_type -> credo.consent.v1.HasConsentResponse
	5,  // 27: credo.consent.v1.ConsentService.RequireConsent:output_type -> credo.consent.v1.RequireConsentResponse
	7,  // 28: credo.consent.v1.ConsentService.GrantConsent:output_type -> credo.consent.v1.GrantConsentResponse
	9,  // 29: credo.consent.v1.ConsentService.RevokeConsent:output_type -> credo.consent.v1.RevokeConsentResponse
	11, // 30: credo.consent.v1.ConsentService.ListConsents:output_type -> credo.consent.v1.ListConsentsResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_api_proto_consent_proto_init() }
func file_api_proto_consent_proto_init() {
	if File_api_proto_consent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_consent_proto_rawDesc), len(file_api_proto_consent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_consent_proto_goTypes,
		DependencyIndexes: file_api_proto_consent_proto_depIdxs,
		EnumInfos:         file_api_proto_consent_proto_enumTypes,
		MessageInfos:      file_api_proto_consent_proto_msgTypes,
	}.Build()
	File_api_proto_consent_proto = out.File
	file_api_proto_consent_proto_goTypes = nil
	file_api_proto_consent_proto_depIdxs = nil
}
