// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/proto/consent.proto

package consentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsentService_HasConsent_FullMethodName     = "/credo.consent.v1.ConsentService/HasConsent"
	ConsentService_RequireConsent_FullMethodName = "/credo.consent.v1.ConsentService/RequireConsent"
	ConsentService_GrantConsent_FullMethodName   = "/credo.consent.v1.ConsentService/GrantConsent"
	ConsentService_RevokeConsent_FullMethodName  = "/credo.consent.v1.ConsentService/RevokeConsent"
	ConsentService_ListConsents_FullMethodName   = "/credo.consent.v1.ConsentService/ListConsents"
)

// ConsentServiceClient is the client API for ConsentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConsentService handles purpose-based consent management
// Used internally by other services (registry, vc, decision)
type ConsentServiceClient interface {
	// Check if user has active consent for a purpose
	HasConsent(ctx context.Context, in *HasConsentRequest, opts ...grpc.CallOption) (*HasConsentResponse, error)
	// Require consent or return error (enforcement)
	RequireConsent(ctx context.Context, in *RequireConsentRequest, opts ...grpc.CallOption) (*RequireConsentResponse, error)
	// Grant consent for purposes (internal operation)
	GrantConsent(ctx context.Context, in *GrantConsentRequest, opts ...grpc.CallOption) (*GrantConsentResponse, error)
	// Revoke consent for purposes (internal operation)
	RevokeConsent(ctx context.Context, in *RevokeConsentRequest, opts ...grpc.CallOption) (*RevokeConsentResponse, error)
	// List all consents for a user
	ListConsents(ctx context.Context, in *ListConsentsRequest, opts ...grpc.CallOption) (*ListConsentsResponse, error)
}

type consentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsentServiceClient(cc grpc.ClientConnInterface) ConsentServiceClient {
	return &consentServiceClient{cc}
}

func (c *consentServiceClient) HasConsent(ctx context.Context, in *HasConsentRequest, opts ...grpc.CallOption) (*HasConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_HasConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) RequireConsent(ctx context.Context, in *RequireConsentRequest, opts ...grpc.CallOption) (*RequireConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequireConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_RequireConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) GrantConsent(ctx context.Context, in *GrantConsentRequest, opts ...grpc.CallOption) (*GrantConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_GrantConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) RevokeConsent(ctx context.Context, in *RevokeConsentRequest, opts ...grpc.CallOption) (*RevokeConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_RevokeConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) ListConsents(ctx context.Context, in *ListConsentsRequest, opts ...grpc.CallOption) (*ListConsentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsentsResponse)
	err := c.cc.Invoke(ctx, ConsentService_ListConsents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsentServiceServer is the server API for ConsentService service.
// All implementations must embed UnimplementedConsentServiceServer
// for forward compatibility.
//
// ConsentService handles purpose-based consent management
// Used internally by other services (registry, vc, decision)
type ConsentServiceServer interface {
	// Check if user has active consent for a purpose
	HasConsent(context.Context, *HasConsentRequest) (*HasConsentResponse, error)
	// Require consent or return error (enforcement)
	RequireConsent(context.Context, *RequireConsentRequest) (*RequireConsentResponse, error)
	// Grant consent for purposes (internal operation)
	GrantConsent(context.Context, *GrantConsentRequest) (*GrantConsentResponse, error)
	// Revoke consent for purposes (internal operation)
	RevokeConsent(context.Context, *RevokeConsentRequest) (*RevokeConsentResponse, error)
	// List all consents for a user
	ListConsents(context.Context, *ListConsentsRequest) (*ListConsentsResponse, error)
	mustEmbedUnimplementedConsentServiceServer()
}

// UnimplementedConsentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsentServiceServer struct{}

func (UnimplementedConsentServiceServer) HasConsent(context.Context, *HasConsentRequest) (*HasConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasConsent not implemented")
}
func (UnimplementedConsentServiceServer) RequireConsent(context.Context, *RequireConsentRequest) (*RequireConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequireConsent not implemented")
}
func (UnimplementedConsentServiceServer) GrantConsent(context.Context, *GrantConsentRequest) (*GrantConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantConsent not implemented")
}
func (UnimplementedConsentServiceServer) RevokeConsent(context.Context, *RevokeConsentRequest) (*RevokeConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeConsent not implemented")
}
func (UnimplementedConsentServiceServer) ListConsents(context.Context, *ListConsentsRequest) (*ListConsentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsents not implemented")
}
func (UnimplementedConsentServiceServer) mustEmbedUnimplementedConsentServiceServer() {}
func (UnimplementedConsentServiceServer) testEmbeddedByValue()                        {}

// UnsafeConsentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsentServiceServer will
// result in compilation errors.
type UnsafeConsentServiceServer interface {
	mustEmbedUnimplementedConsentServiceServer()
}

func RegisterConsentServiceServer(s grpc.ServiceRegistrar, srv ConsentServiceServer) {
	// If the following call panics, it indicates UnimplementedConsentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsentService_ServiceDesc, srv)
}

func _ConsentService_HasConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).HasConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_HasConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).HasConsent(ctx, req.(*HasConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_RequireConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequireConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).RequireConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_RequireConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).RequireConsent(ctx, req.(*RequireConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_GrantConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).GrantConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_GrantConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).GrantConsent(ctx, req.(*GrantConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_RevokeConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).RevokeConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_RevokeConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).RevokeConsent(ctx, req.(*RevokeConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_ListConsents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).ListConsents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_ListConsents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).ListConsents(ctx, req.(*ListConsentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsentService_ServiceDesc is the grpc.ServiceDesc for ConsentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "credo.consent.v1.ConsentService",
	HandlerType: (*ConsentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasConsent",
			Handler:    _ConsentService_HasConsent_Handler,
		},
		{
			MethodName: "RequireConsent",
			Handler:    _ConsentService_RequireConsent_Handler,
		},
		{
			MethodName: "GrantConsent",
			Handler:    _ConsentService_GrantConsent_Handler,
		},
		{
			MethodName: "RevokeConsent",
			Handler:    _ConsentService_RevokeConsent_Handler,
		},
		{
			MethodName: "ListConsents",
			Handler:    _ConsentService_ListConsents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/consent.proto",
}
