// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/proto/registry.proto

package registrypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistryService_CheckCitizen_FullMethodName   = "/credo.registry.v1.RegistryService/CheckCitizen"
	RegistryService_CheckSanctions_FullMethodName = "/credo.registry.v1.RegistryService/CheckSanctions"
	RegistryService_Check_FullMethodName          = "/credo.registry.v1.RegistryService/Check"
)

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RegistryService handles citizen and sanctions registry lookups
// Used internally by decision engine and VC issuance
type RegistryServiceClient interface {
	// Check citizen record
	CheckCitizen(ctx context.Context, in *CheckCitizenRequest, opts ...grpc.CallOption) (*CheckCitizenResponse, error)
	// Check sanctions record
	CheckSanctions(ctx context.Context, in *CheckSanctionsRequest, opts ...grpc.CallOption) (*CheckSanctionsResponse, error)
	// Combined check (citizen + sanctions)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type registryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryServiceClient(cc grpc.ClientConnInterface) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) CheckCitizen(ctx context.Context, in *CheckCitizenRequest, opts ...grpc.CallOption) (*CheckCitizenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCitizenResponse)
	err := c.cc.Invoke(ctx, RegistryService_CheckCitizen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) CheckSanctions(ctx context.Context, in *CheckSanctionsRequest, opts ...grpc.CallOption) (*CheckSanctionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSanctionsResponse)
	err := c.cc.Invoke(ctx, RegistryService_CheckSanctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, RegistryService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
// All implementations must embed UnimplementedRegistryServiceServer
// for forward compatibility.
//
// RegistryService handles citizen and sanctions registry lookups
// Used internally by decision engine and VC issuance
type RegistryServiceServer interface {
	// Check citizen record
	CheckCitizen(context.Context, *CheckCitizenRequest) (*CheckCitizenResponse, error)
	// Check sanctions record
	CheckSanctions(context.Context, *CheckSanctionsRequest) (*CheckSanctionsResponse, error)
	// Combined check (citizen + sanctions)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedRegistryServiceServer()
}

// UnimplementedRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistryServiceServer struct{}

func (UnimplementedRegistryServiceServer) CheckCitizen(context.Context, *CheckCitizenRequest) (*CheckCitizenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCitizen not implemented")
}
func (UnimplementedRegistryServiceServer) CheckSanctions(context.Context, *CheckSanctionsRequest) (*CheckSanctionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSanctions not implemented")
}
func (UnimplementedRegistryServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedRegistryServiceServer) mustEmbedUnimplementedRegistryServiceServer() {}
func (UnimplementedRegistryServiceServer) testEmbeddedByValue()                         {}

// UnsafeRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServiceServer will
// result in compilation errors.
type UnsafeRegistryServiceServer interface {
	mustEmbedUnimplementedRegistryServiceServer()
}

func RegisterRegistryServiceServer(s grpc.ServiceRegistrar, srv RegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistryService_ServiceDesc, srv)
}

func _RegistryService_CheckCitizen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCitizenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).CheckCitizen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_CheckCitizen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).CheckCitizen(ctx, req.(*CheckCitizenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_CheckSanctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSanctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).CheckSanctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_CheckSanctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).CheckSanctions(ctx, req.(*CheckSanctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistryService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistryService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistryService_ServiceDesc is the grpc.ServiceDesc for RegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "credo.registry.v1.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckCitizen",
			Handler:    _RegistryService_CheckCitizen_Handler,
		},
		{
			MethodName: "CheckSanctions",
			Handler:    _RegistryService_CheckSanctions_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _RegistryService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/registry.proto",
}
