// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/registry.proto

package registrypb

import (
	common "github.com/credo/gateway/api/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckCitizenRequest checks citizen registry
type CheckCitizenRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NationalId    string                  `protobuf:"bytes,2,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCitizenRequest) Reset() {
	*x = CheckCitizenRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCitizenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCitizenRequest) ProtoMessage() {}

func (x *CheckCitizenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCitizenRequest.ProtoReflect.Descriptor instead.
func (*CheckCitizenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{0}
}

func (x *CheckCitizenRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CheckCitizenRequest) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

type CheckCitizenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Citizen       *CitizenRecord         `protobuf:"bytes,1,opt,name=citizen,proto3" json:"citizen,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCitizenResponse) Reset() {
	*x = CheckCitizenResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCitizenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCitizenResponse) ProtoMessage() {}

func (x *CheckCitizenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCitizenResponse.ProtoReflect.Descriptor instead.
func (*CheckCitizenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{1}
}

func (x *CheckCitizenResponse) GetCitizen() *CitizenRecord {
	if x != nil {
		return x.Citizen
	}
	return nil
}

func (x *CheckCitizenResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

// CheckSanctionsRequest checks sanctions registry
type CheckSanctionsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NationalId    string                  `protobuf:"bytes,2,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSanctionsRequest) Reset() {
	*x = CheckSanctionsRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSanctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSanctionsRequest) ProtoMessage() {}

func (x *CheckSanctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSanctionsRequest.ProtoReflect.Descriptor instead.
func (*CheckSanctionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{2}
}

func (x *CheckSanctionsRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CheckSanctionsRequest) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

type CheckSanctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sanctions     *SanctionsRecord       `protobuf:"bytes,1,opt,name=sanctions,proto3" json:"sanctions,omitempty"`
	FromCache     bool                   `protobuf:"varint,2,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSanctionsResponse) Reset() {
	*x = CheckSanctionsResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSanctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSanctionsResponse) ProtoMessage() {}

func (x *CheckSanctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSanctionsResponse.ProtoReflect.Descriptor instead.
func (*CheckSanctionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{3}
}

func (x *CheckSanctionsResponse) GetSanctions() *SanctionsRecord {
	if x != nil {
		return x.Sanctions
	}
	return nil
}

func (x *CheckSanctionsResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

// CheckRequest performs combined check
type CheckRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metadata      *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NationalId    string                  `protobuf:"bytes,2,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{4}
}

func (x *CheckRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CheckRequest) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Citizen       *CitizenRecord         `protobuf:"bytes,1,opt,name=citizen,proto3" json:"citizen,omitempty"`
	Sanctions     *SanctionsRecord       `protobuf:"bytes,2,opt,name=sanctions,proto3" json:"sanctions,omitempty"`
	FromCache     bool                   `protobuf:"varint,3,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{5}
}

func (x *CheckResponse) GetCitizen() *CitizenRecord {
	if x != nil {
		return x.Citizen
	}
	return nil
}

func (x *CheckResponse) GetSanctions() *SanctionsRecord {
	if x != nil {
		return x.Sanctions
	}
	return nil
}

func (x *CheckResponse) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

// CitizenRecord (minimized for internal use)
// In regulated mode, only 'valid' and 'national_id' are populated
type CitizenRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NationalId    string                 `protobuf:"bytes,1,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`            // Empty in regulated mode
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"` // Empty in regulated mode (format: YYYY-MM-DD)
	Valid         bool                   `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CitizenRecord) Reset() {
	*x = CitizenRecord{}
	mi := &file_api_proto_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CitizenRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenRecord) ProtoMessage() {}

func (x *CitizenRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenRecord.ProtoReflect.Descriptor instead.
func (*CitizenRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{6}
}

func (x *CitizenRecord) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

func (x *CitizenRecord) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CitizenRecord) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CitizenRecord) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CitizenRecord) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

// SanctionsRecord (no PII, safe for any mode)
type SanctionsRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NationalId    string                 `protobuf:"bytes,1,opt,name=national_id,json=nationalId,proto3" json:"national_id,omitempty"`
	Listed        bool                   `protobuf:"varint,2,opt,name=listed,proto3" json:"listed,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanctionsRecord) Reset() {
	*x = SanctionsRecord{}
	mi := &file_api_proto_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanctionsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanctionsRecord) ProtoMessage() {}

func (x *SanctionsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanctionsRecord.ProtoReflect.Descriptor instead.
func (*SanctionsRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{7}
}

func (x *SanctionsRecord) GetNationalId() string {
	if x != nil {
		return x.NationalId
	}
	return ""
}

func (x *SanctionsRecord) GetListed() bool {
	if x != nil {
		return x.Listed
	}
	return false
}

func (x *SanctionsRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SanctionsRecord) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

var File_api_proto_registry_proto protoreflect.FileDescriptor

const file_api_proto_registry_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/registry.proto\x12\x11credo.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16api/proto/common.proto\"t\n" +
	"\x13CheckCitizenRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x1f\n" +
	"\vnational_id\x18\x02 \x01(\tR\n" +
	"nationalId\"q\n" +
	"\x14CheckCitizenResponse\x12:\n" +
	"\acitizen\x18\x01 \x01(\v2 .credo.registry.v1.CitizenRecordR\acitizen\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache\"v\n" +
	"\x15CheckSanctionsRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x1f\n" +
	"\vnational_id\x18\x02 \x01(\tR\n" +
	"nationalId\"y\n" +
	"\x16CheckSanctionsResponse\x12@\n" +
	"\tsanctions\x18\x01 \x01(\v2\".credo.registry.v1.SanctionsRecordR\tsanctions\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x02 \x01(\bR\tfromCache\"m\n" +
	"\fCheckRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2 .credo.common.v1.RequestMetadataR\bmetadata\x12\x1f\n" +
	"\vnational_id\x18\x02 \x01(\tR\n" +
	"nationalId\"\xac\x01\n" +
	"\rCheckResponse\x12:\n" +
	"\acitizen\x18\x01 \x01(\v2 .credo.registry.v1.CitizenRecordR\acitizen\x12@\n" +
	"\tsanctions\x18\x02 \x01(\v2\".credo.registry.v1.SanctionsRecordR\tsanctions\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x03 \x01(\bR\tfromCache\"\xc2\x01\n" +
	"\rCitizenRecord\x12\x1f\n" +
	"\vnational_id\x18\x01 \x01(\tR\n" +
	"nationalId\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\x12\x14\n" +
	"\x05valid\x18\x04 \x01(\bR\x05valid\x129\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"\x9d\x01\n" +
	"\x0fSanctionsRecord\x12\x1f\n" +
	"\vnational_id\x18\x01 \x01(\tR\n" +
	"nationalId\x12\x16\n" +
	"\x06listed\x18\x02 \x01(\bR\x06listed\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x129\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt2\xa5\x02\n" +
	"\x0fRegistryService\x12_\n" +
	"\fCheckCitizen\x12&.credo.registry.v1.CheckCitizenRequest\x1a'.credo.registry.v1.CheckCitizenResponse\x12e\n" +
	"\x0eCheckSanctions\x12(.credo.registry.v1.CheckSanctionsRequest\x1a).credo.registry.v1.CheckSanctionsResponse\x12J\n" +
	"\x05Check\x12\x1f.credo.registry.v1.CheckRequest\x1a .credo.registry.v1.CheckResponseB8Z6github.com/credo/gateway/api/proto/registry;registrypbb\x06proto3"

var (
	file_api_proto_registry_proto_rawDescOnce sync.Once
	file_api_proto_registry_proto_rawDescData []byte
)

func file_api_proto_registry_proto_rawDescGZIP() []byte {
	file_api_proto_registry_proto_rawDescOnce.Do(func() {
		file_api_proto_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_registry_proto_rawDesc), len(file_api_proto_registry_proto_rawDesc)))
	})
	return file_api_proto_registry_proto_rawDescData
}

var file_api_proto_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_registry_proto_goTypes = []any{
	(*CheckCitizenRequest)(nil),    // 0: credo.registry.v1.CheckCitizenRequest
	(*CheckCitizenResponse)(nil),   // 1: credo.registry.v1.CheckCitizenResponse
	(*CheckSanctionsRequest)(nil),  // 2: credo.registry.v1.CheckSanctionsRequest
	(*CheckSanctionsResponse)(nil), // 3: credo.registry.v1.CheckSanctionsResponse
	(*CheckRequest)(nil),           // 4: credo.registry.v1.CheckRequest
	(*CheckResponse)(nil),          // 5: credo.registry.v1.CheckResponse
	(*CitizenRecord)(nil),          // 6: credo.registry.v1.CitizenRecord
	(*SanctionsRecord)(nil),        // 7: credo.registry.v1.SanctionsRecord
	(*common.RequestMetadata)(nil), // 8: credo.common.v1.RequestMetadata
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_api_proto_registry_proto_depIdxs = []int32{
	8,  // 0: credo.registry.v1.CheckCitizenRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	6,  // 1: credo.registry.v1.CheckCitizenResponse.citizen:type_name -> credo.registry.v1.CitizenRecord
	8,  // 2: credo.registry.v1.CheckSanctionsRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	7,  // 3: credo.registry.v1.CheckSanctionsResponse.sanctions:type_name -> credo.registry.v1.SanctionsRecord
	8,  // 4: credo.registry.v1.CheckRequest.metadata:type_name -> credo.common.v1.RequestMetadata
	6,  // 5: credo.registry.v1.CheckResponse.citizen:type_name -> credo.registry.v1.CitizenRecord
	7,  // 6: credo.registry.v1.CheckResponse.sanctions:type_name -> credo.registry.v1.SanctionsRecord
	9,  // 7: credo.registry.v1.CitizenRecord.checked_at:type_name -> google.protobuf.Timestamp
	9,  // 8: credo.registry.v1.SanctionsRecord.checked_at:type_name -> google.protobuf.Timestamp
	0,  // 9: credo.registry.v1.RegistryService.CheckCitizen:input_type -> credo.registry.v1.CheckCitizenRequest
	2,  // 10: credo.registry.v1.RegistryService.CheckSanctions:input_type -> credo.registry.v1.CheckSanctionsRequest
	4,  // 11: credo.registry.v1.RegistryService.Check:input_type -> credo.registry.v1.CheckRequest
	1,  // 12: credo.registry.v1.RegistryService.CheckCitizen:output_type -> credo.registry.v1.CheckCitizenResponse
	3,  // 13: credo.registry.v1.RegistryService.CheckSanctions:output_type -> credo.registry.v1.CheckSanctionsResponse
	5,  // 14: credo.registry.v1.RegistryService.Check:output_type -> credo.registry.v1.CheckResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_registry_proto_init() }
func file_api_proto_registry_proto_init() {
	if File_api_proto_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_registry_proto_rawDesc), len(file_api_proto_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_registry_proto_goTypes,
		DependencyIndexes: file_api_proto_registry_proto_depIdxs,
		MessageInfos:      file_api_proto_registry_proto_msgTypes,
	}.Build()
	File_api_proto_registry_proto = out.File
	file_api_proto_registry_proto_goTypes = nil
	file_api_proto_registry_proto_depIdxs = nil
}
