// Code generated by MockGen. DO NOT EDIT.
// Source: handlers_consent.go
//
// Generated by this command:
//
//	mockgen -source=handlers_consent.go -destination=mocks/consent-mocks.go -package=mocks ConsentService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "id-gateway/internal/consent/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockConsentService is a mock of ConsentService interface.
type MockConsentService struct {
	ctrl     *gomock.Controller
	recorder *MockConsentServiceMockRecorder
	isgomock struct{}
}

// MockConsentServiceMockRecorder is the mock recorder for MockConsentService.
type MockConsentServiceMockRecorder struct {
	mock *MockConsentService
}

// NewMockConsentService creates a new mock instance.
func NewMockConsentService(ctrl *gomock.Controller) *MockConsentService {
	mock := &MockConsentService{ctrl: ctrl}
	mock.recorder = &MockConsentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsentService) EXPECT() *MockConsentServiceMockRecorder {
	return m.recorder
}

// Grant mocks base method.
func (m *MockConsentService) Grant(ctx context.Context, userID string, purposes []models.ConsentPurpose, ttl time.Duration) ([]*models.ConsentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grant", ctx, userID, purposes, ttl)
	ret0, _ := ret[0].([]*models.ConsentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grant indicates an expected call of Grant.
func (mr *MockConsentServiceMockRecorder) Grant(ctx, userID, purposes, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grant", reflect.TypeOf((*MockConsentService)(nil).Grant), ctx, userID, purposes, ttl)
}

// List mocks base method.
func (m *MockConsentService) List(ctx context.Context, userID string) ([]*models.ConsentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]*models.ConsentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockConsentServiceMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConsentService)(nil).List), ctx, userID)
}

// Require mocks base method.
func (m *MockConsentService) Require(ctx context.Context, userID string, purpose models.ConsentPurpose, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Require", ctx, userID, purpose, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Require indicates an expected call of Require.
func (mr *MockConsentServiceMockRecorder) Require(ctx, userID, purpose, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Require", reflect.TypeOf((*MockConsentService)(nil).Require), ctx, userID, purpose, now)
}

// Revoke mocks base method.
func (m *MockConsentService) Revoke(ctx context.Context, userID string, purpose models.ConsentPurpose) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, userID, purpose)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockConsentServiceMockRecorder) Revoke(ctx, userID, purpose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockConsentService)(nil).Revoke), ctx, userID, purpose)
}
